### ISSUE TITLE
How should the structure of UME::SIMD in /usr/include be?

### ISSUE THREAD

**Issue by marehr** [edanor/umesimd#47]
Hi Przemyslaw,

I came across the problem, how to include UME::SIMD in my programs. As an example, we have in our repository the folder structure `/include/seqan` that means the distributors can copy all our header files from there to some common `/include` folder (e.g. `/usr/include`, if you install `apt-get install seqan-dev` you will find our header files in in that folder).

In the source code, you can include the headers like this:
``` c++
#include <seqan/bam_io.h>
// ....
```
See http://seqan.readthedocs.io/en/master/Tutorial/InputOutput/FileIOOverview.html for an example.

Your repository has no obvious `/include` folder.

So, do you want that users include as
```c++
#include <umesimd/UMESimd.h> // so?
#include <UMESimd/UMESimd.h> // or, so?
#include <UMESimd.h> // or, so?
```

----

I looked into some projects, how they handle it (the part in [] is what will be copied over):

* [mysql](https://github.com/mysql/mysql-server): has `/include/[**.h]` in the repository, installs as `/usr/include/mysql/[**.h]`
* [protobuf](https://github.com/google/protobuf): has `/src/[google/protobuf/**.h]`which will (partially) be copied to `/usr/include/[google/protobuf/**.h]`
* [poppler](https://github.com/davidben/poppler): has `[/glib/**.h]` -> `/usr/include/poppler/[glib/**.h]`
* [boost](https://github.com/boostorg/boost): Is a collection of repositories that follow the same rule
    * For example [hana](https://github.com/boostorg/hana) has `/include/[boost/**.h]` -> `/usr/include/[boost/**.h]`

Thus, there are different philosophies how to address this. I'd say that purely C++ written libraries will most likely have a dedicated `/include` folder, but there is no common pattern if they will have the library name included in `/include/[umesimd?]`.

**Comment by edanor** [comment]
This is a very snake-like question, and I have no straightforward answer here. I guess at some point a decision will have to be made to deal with that, but I am not sure if the moment is right now.

UME::SIMD is include-only library (by design and by commitment), so there are only few files, such as microbenchmarks or unit tests, which are not required for the library core functionality. Since they represent only a tiny fraction of the library size, there is really no need to exclude them from the installation process. This means that the only thing the installation procedure would perform, would be to copy whole file hierarchy to some place pointed by the user, and perhaps setup some environmental variables (i. e. _CPLUS_INCLUDE_PATH_). Because doing so is highly system dependent there is no easy way to handle that in an automated way.

For now you should stick to:
`#include <umesimd/UMESimd.h> `

I am planning to create a full framework (e.g. prototype for next work-piece: [UME::VECTOR](https://bitbucket.org/edanor/umevector) in which case the include hierarchy would get more complicated. So if you have many places where you include UME::SIMD library, then this would make your life easier when possibly switching to a full framework.

**Comment by edanor** [comment]
I've added the ume/ directory to the install structure, so that it would be possible to add modules, such as ume/simd or ume/vector without future changes to existing modules structure. Hope this will solve your problem definitely.

If you need anything further for the installation file, please suggest specific changes.
