### ISSUE TITLE
Does not compile with GCC 6.2.0 on Knights Landing

### ISSUE THREAD

**Issue by noma** [edanor/umesimd#6]
Here's the rather long build log:

[gcc_6.2.0_umesimd_build_log_knl.txt](https://github.com/edanor/umesimd/files/540559/gcc_6.2.0_umesimd_build_log_knl.txt)

**Comment by edanor** [comment]
It seems like gcc is using different parameter types for address field for gather/scatter address operands. This seems like a compiler issue. The same problem is not exposing itself with clang and icc, and ICC reference manual clearly states these types to be 'void *'.

I've added workaround, so that it would be possible to use g++.

I am really surprised though, that unit tests didn't catch this.

**Comment by noma** [comment]
Thanks, works now with your fix, maybe you can file a bug for GCC.
