### ISSUE TITLE
QuadraticSolver generates incorrect roots with g++ on KNL

### ISSUE THREAD

**Issue by rscottmanley** [edanor/umesimd#64]
Hello, I have noticed that certain seed values can cause invalid results on KNL with g++ with optimization turned on.

For example, in QuadraticSolverAVXx.h::run_AVX512(), 

```
    //unsigned int tseed = (unsigned int) time (NULL);
    unsigned int tseed = 1493656643;
    srand(tseed);
```

Compile line:
 g++ -O2  QuadraticSolver.cpp -march=knl

Will cause an invalid result during QuadSolveNaive verification. This is my own debug output:

```
Result invalid! (roots: 1 expected: 2
time seed 1493656643
    i = 2915214
 a[i] = 1.375663
 b[i] = -2.976534
 c[i] = 1.610088
x1[i] = 1.081855
x2[i] = 1.081855
   t0 = 1.081628
   t1 = 1.082081
```
 
This is both natively on KNL hardware and via Intel's SDE. G++ seems to generate correct results without optimization, however Intel 17 at -O2 does not generate bad results with the same seed value.

**Comment by edanor** [comment]
Hi, thanks for pointing this out. This seems like an interesting, case to study.

The problem seems to be algorithm stability issue and I am afraid there is no solution that would be both fast and precise. I was also able to reproduce this problem with ICC.

If we print the solutions for both reference (QuadSolveNaive) and the faulting AVX code (QuadSolveAVXx) we have following solutions:

Naive: 

    b2 = b*b = 8.8597536
    ac = a*c = 2.2149384
    delta_naive: 3.8824874e-07
    x1[i]: 1.0816282
    x2[i]: 1.0820810

AVX512 intrinsics:

    b2 = b*b = 8.8597536
    ac = a*c = 2.2149384
    delta_avx512: 0
    x1[i]: 1.0818546
    x2[i]: 1.0818546

So indeed in the first case the number of distinct solutions is 2, while in the second case we obtain the same root twice. Let's try calculating this with higher precision (64b):

    delta_true= b*b - 4*a*c == (-2.9765339)*(-2.9765339) - ((4*1.3756627)*1.6100883) = 0.00000038578357
    sqrt(delta)=6.2111478005276931261981513275665e-4
    x1 = (-b - sqrt(delta))/2*a = (2.9765339 - 6.2111478005276931261981513275665e-4)/(2*1.375663) = 1.0816285620896786606484946476235 ~= 1.0816285
    x2 = (-b + sqrt(delta))/2*a = (2.9765339 + 6.2111478005276931261981513275665e-4)/(2*1.375663) = 1.0820800

Two solutions are very close to the true values.

If we now look at delta:

    delta_true= b*b - 4*a*c == (-2.9765339)*(-2.9765339) - (4*(1.3756627*1.6100883)) = 0.00000038578357

the approximation error is:

    |delta_naive - delta_true| = 0.00000000246517



Now for the AVX512 version

    |delta_avx512 - delta_true| = 0.00000038578357

Indeed the later one is less precise. Let's see what values we are getting from the hardware:

    b2 = b*b = 8.8597536
    ac = a*c = 2.2149384

    delta_avx512 = b2 -4*ac = 8.8597536 - 4*2.2149384=0 

The errors of evaluation of b2 and ac:
    err_b2 = |8.8597536 - 8.85975405784921| = 0.00000045784921
    err_ac = |2.2149384 - 2.21493841801641| = 0.00000001801641

Looking at the two values above, we can see that cumulative error could be as large as:

    err = err_b2 + 4*err_ac = 0.00000052991485

and it definitely is larger than error on delta.

If we assume:
delta_avx512 = err = 0.00000052991485

We then obtain two solutions:

    x1 = 1.0815899666010720299980737240568
    x2 = 1.0821191315666692339033172201041

which is a much better approximation of our two solutions. 

This suggests that the problem is in the way the compiler handles error propagation. If I remember correctly IEEE 754 defines that in case of expressions, the result should be calculated as if the actual precision of constituent operations was performed using extended precision. Guess the compiler/microarchitecture is making a shortcut here for performance.

Now as for some practical solutions:
For ICC replacing '-fp-model=precise' flag with '-mieee-fp' seems to be helping.
For GCC i haven't found any proper documentation, and it seems that the only possible flag '-fexcess-precision=standard' is not implemented (I'm using GCC 5.3, so it could work for 6.x).

As for the fixes in the code: I am slowly switching this benchmarks to an evaluation mode where both performance and accuracy are measured. Unfortunately the solution becomes uncertain when both poles are extremaly close to each other, so the only real solution is to extend the precision, and therefore stabilise an algorithm.

Let me know if this helps you in any way.

**Comment by rscottmanley** [comment]
Thank you for the response. I was looking to confirm that this code was numerically sensitive to optimizations so I can run it at lower optimization levels and seems to give me the correct results. 

Cheers.

**Comment by edanor** [comment]
I can confirm now: the algorithm itself is not stable. See _Higham A. Accuracy and Stability of Numerical Algorithms_ for reference.

I'll look for some other results comparison method to see whether these error message can be supressed.
